import { supabase } from './supabase';

export interface Incident {
  id?: string; // Generated by Supabase (uuid)
  type: string;
  latitude: number;
  longitude: number;
  description: string;
  severity: number;
  created_at?: string; // Generated by Supabase (timestamptz)
}

/**
 * Fetch all incidents from the database, ordered by latest first
 */
export const fetchIncidents = async (): Promise<Incident[]> => {
  try {
    const { data, error } = await supabase
      .from('incidents')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Supabase Query Error (Fetch):', error.message);
      throw error;
    }

    return data as Incident[];
  } catch (err: any) {
    console.error('Failed to fetch incidents:', err.message);
    return [];
  }
};

/**
 * Insert a new incident report
 */
export const createIncident = async (
  incident: Omit<Incident, 'id' | 'created_at'>
): Promise<Incident | null> => {
  try {
    const { data, error } = await supabase
      .from('incidents')
      .insert([incident])
      .select()
      .single(); // returns the newly created row

    if (error) {
      console.error('Supabase Query Error (Insert):', error.message);
      throw error;
    }

    return data as Incident;
  } catch (err: any) {
    console.error('Failed to create incident:', err.message);
    throw err;
  }
};

/**
 * Subscribe to real-time changes on the "incidents" table
 * @param onUpdate Callback fired when an INSERT, UPDATE, or DELETE happens
 * @returns a function to unsubscribe from the real-time channel
 */
export const subscribeToIncidents = (onUpdate: (payload: any) => void) => {
  const channel = supabase
    .channel('public:incidents')
    .on(
      // The Postgres Changes extension allows listening to all real-time events on the table
      'postgres_changes',
      { event: '*', schema: 'public', table: 'incidents' },
      (payload) => {
        console.log('Real-time incident update received:', payload.eventType);
        onUpdate(payload);
      }
    )
    .subscribe();

  // Return unsubscribe cleanup function
  return () => {
    supabase.removeChannel(channel);
  };
};
